#!/usr/bin/env zsh
year=2025
mkdir -p "$year"
cd "$year"
for i in {01..12}
do
    name="advent_${year}_${i}"
    mkdir -p "day$i"
    cargo generate --path ../template --name $name --destination "day$i" --init
done
