[package]
name = "advent_2021_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
ansi_term = "0.12.1"
nom = { workspace = true }
nom_locate = "4"
