[package]
name = "advent_2024_24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
nom = { workspace = true }
itertools = { workspace = true }
