[package]
name = "advent_2015_12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
nom = { workspace = true }
serde = "1.0.197"
serde_json = "1.0.113"
