[package]
name = "advent_2021_22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
counter = "0.6.0"
nom = { workspace = true }
