[package]
name = "advent_2017_14"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
advent_2017_10 = { path = "../day10" }
nom = { workspace = true }
