[package]
name = "advent_2018_19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
advent_2018_16 = { path = "../day16" }
nom = { workspace = true }
