[package]
name = "advent_2018_23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
nom = "7"
z3 = { version = "0.12.1" }
